### ISSUE TITLE
How to combine this with keyboard

### ISSUE THREAD

**Issue by hha1** [examus/mouse-stick#3]
I see about keyboard on this website. Do you know how to combine the two together？
[USBKeyboard](https://github.com/coopermaa/USBKeyboard)

**Comment by shofel** [comment]
Please expand your intention, and maybe we together find a way to do the trick.

**Comment by shofel** [comment]
I think, here is a way to turn a joystick to a keyboard :D
https://play.google.com/store/apps/details?id=com.exideas.mekb

**Comment by hha1** [comment]
> Please expand your intention, and maybe we together find a way to do the trick.
I found a new example and have tried to implement it. But when I use flip to upload hex files, I will be prompted "invalid HEX file syntax". Do you know what's going on？
This is the website:[HID](https://github.com/NicoHood/HID)

**Comment by shofel** [comment]
Closing for housekeeping reasons.
